version: '3.8'

services:
  rimworld-together:
    image: rimworld-together:latest
    container_name: rimworld-together
    ports:
      - "25555:25555"  # Map port 25555 from host to container
    volumes:
      - data:/opt/rimworld-together/Data
    restart: unless-stopped  # Automatically restart the container if it stops

volumes:
  data: