name: Build and Push Docker Image

on:
  # Trigger the workflow on a push to the main branch or on pull requests
  push:
    branches:
      - main
  pull_request:

  # Allow the workflow to be triggered manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Make build.sh executable
      - name: Make build.sh executable
        run: chmod +x ./build.sh

      # Step 4: Run build.sh (this should build and tag images for GHCR)
      - name: Run build.sh
        run: ./build.sh

      # Step 5: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Push all Docker image tags (filtered for ghcr.io)
      - name: Push all Docker image tags
        run: |
          # List all local images tagged for ghcr.io and push them
          docker images --format "{{.Repository}}:{{.Tag}}" | grep "ghcr.io" | while read -r image; do
            docker push "$image"
          done
