name: Build and Push Docker Image

on:
  # Trigger the workflow on a push to the main branch or on pull requests
  push:
    branches:
      - main
  pull_request:

  # Allow the workflow to be triggered manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Fetch the latest release version from GitHub API
      - name: Get latest release version
        id: get_version
        run: |
          VERSION=$(curl -s https://api.github.com/repos/Byte-Nova/Rimworld-Together/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          if [ -z "$VERSION" ]; then
            echo "Failed to fetch version from GitHub."
            exit 1
          fi
          echo "Latest version is $VERSION."
          echo "::set-output name=VERSION::$VERSION"

      # Step 4: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Build the Docker image with both the version and latest tags
      - name: Build Docker image
        run: |
          docker build --build-arg VERSION=${{ steps.get_version.outputs.VERSION }} -t ghcr.io/${{ github.actor }}/rimworld-together:${{ steps.get_version.outputs.VERSION }} .
          docker tag ghcr.io/${{ github.actor }}/rimworld-together:${{ steps.get_version.outputs.VERSION }} ghcr.io/${{ github.actor }}/rimworld-together:latest

      # Step 6: Push the Docker image to GHCR (both version and latest tags)
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.actor }}/rimworld-together:${{ steps.get_version.outputs.VERSION }}
          docker push ghcr.io/${{ github.actor }}/rimworld-together:latest

